// Code generated by mockery v2.42.3. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// IBoardGenerator is an autogenerated mock type for the IBoardGenerator type
type IBoardGenerator struct {
	mock.Mock
}

// GenerateBoards provides a mock function with given fields:
func (_m *IBoardGenerator) GenerateBoards() {
	_m.Called()
}

// NewIBoardGenerator creates a new instance of IBoardGenerator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIBoardGenerator(t interface {
	mock.TestingT
	Cleanup(func())
}) *IBoardGenerator {
	mock := &IBoardGenerator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
